sonar.organization=annaanjali2
sonar.projectKey=annaanjali2_helloworld-demo-python

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.
