name: devsecops-pipeline
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        
    - name: Secret Scanning
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8.2.1 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}        

  docker-pipeline:
    needs: devsecops-pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0    

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Linting
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

    - name: Docker Build
      run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:latest .

    - name: Docker Images
      run: docker images

    - name: Docker Container
      run: docker run -itd ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:latest

    - name: Docker Container Lists
      run: docker ps

    - name: Docker Push
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:latest
    
