name: devsecops-pipeline
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

permissions:
  contents: read
  id-token: write
  packages: write
  
jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        
    - name: Secret Scanning
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8.2.1 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}        

  docker-pipeline:
    needs: devsecops-pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0    

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Linting
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL4000

    - name: Docker Build
      run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:${{ github.sha }} .

    - name: Docker Images
      run: docker images

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: '${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: SBOM Report Regeration with Syft
      uses: anchore/sbom-action@v0
      with:
        image: '${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:${{ github.sha }}'
        artifact-name: sbom.spdx

    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.1.0
      
    - name: Check Cosign Version
      run: cosign version

    - name: Docker Push
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:${{ github.sha }}
    #   docker push ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:latest
    
    - name: Get Image Digest
      id: digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:${{ github.sha }})
        echo "digest=$DIGEST" >> $GITHUB_OUTPUT

    - name: Cosign Sign Image
      env:
        COSIGN_EXPERIMENTAL: "1"
      run: cosign sign --yes "${{ steps.digest.outputs.digest }}"

    - name: Docker Container
      run: docker run -itd ${{ vars.DOCKERHUB_USERNAME }}/helloworld-demo-python:${{ github.sha }}

    - name: Docker Container Lists
      run: docker ps

  k8s-implementation:
    needs: docker-pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0 

    - name: start minikube
      uses: medyagh/setup-minikube@latest        

    - name: Try the Cluster
      run: kubectl get pods -A

    - name: Kube Brnch
      run: |
        kubectl delete job kube-bench --ignore-not-found=true
        kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/refs/heads/main/job.yaml
        kubectl wait --for=condition=complete job/kube-bench --timeout=180s
        echo "============================== Kube-bench Results ========================="
        kubectl logs job/kube-bench

    - name: Create Deployment and Service
      run: |                     
        kubectl apply -f ./k8s/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
        kubectl wait --for=condition=ready pod -l app=helloworld

    - name: Verify Deploymentt and Service
      run: |
        kubectl get deployments
        kubectl get service

    - name: Test Service URL
      run: |
        minikube service list
        minikube service my-service --url
        echo "--------------------------- Opening the service --------------------"
        curl $(minikube service my-service --url)
      
